// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'rest_timer_service.dart';

// **************************************************************************
// ServiceGenerator
// **************************************************************************

// @FoundryService registration tag for RestTimerService
// stateful: true
// Generated by foundry_generator — do not edit.

// **************************************************************************
// ServiceStateGenerator
// **************************************************************************

// ignore_for_file: unused_element, annotate_overrides, prefer_interpolation_to_compose_strings

// Generated code for @FoundryServiceState RestTimerState

const _$RestTimerStateSentinel = Object();

/// Whether [RestTimerState] should be persisted automatically.
const bool $RestTimerStateIsPersistent = false;

mixin _$RestTimerStateMixin {
  RestTimerState copyWith({
    Object? totalSeconds = _$RestTimerStateSentinel,
    Object? remainingSeconds = _$RestTimerStateSentinel,
    Object? isRunning = _$RestTimerStateSentinel,
    Object? showRestFinishedBanner = _$RestTimerStateSentinel,
  }) {
    final RestTimerState self = this as RestTimerState;
    return RestTimerState(
      totalSeconds: identical(totalSeconds, _$RestTimerStateSentinel)
          ? self.totalSeconds
          : totalSeconds as int,
      remainingSeconds: identical(remainingSeconds, _$RestTimerStateSentinel)
          ? self.remainingSeconds
          : remainingSeconds as int,
      isRunning: identical(isRunning, _$RestTimerStateSentinel)
          ? self.isRunning
          : isRunning as bool,
      showRestFinishedBanner:
          identical(showRestFinishedBanner, _$RestTimerStateSentinel)
          ? self.showRestFinishedBanner
          : showRestFinishedBanner as bool,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other.runtimeType != runtimeType) return false;
    final RestTimerState self = this as RestTimerState;
    return other is RestTimerState &&
        self.totalSeconds == other.totalSeconds &&
        self.remainingSeconds == other.remainingSeconds &&
        self.isRunning == other.isRunning &&
        self.showRestFinishedBanner == other.showRestFinishedBanner;
  }

  @override
  int get hashCode {
    final RestTimerState self = this as RestTimerState;
    return Object.hash(
      self.totalSeconds,
      self.remainingSeconds,
      self.isRunning,
      self.showRestFinishedBanner,
    );
  }

  @override
  String toString() {
    final RestTimerState self = this as RestTimerState;
    final List<String> values = <String>[
      'totalSeconds: ' + self.totalSeconds.toString(),
      'remainingSeconds: ' + self.remainingSeconds.toString(),
      'isRunning: ' + self.isRunning.toString(),
      'showRestFinishedBanner: ' + self.showRestFinishedBanner.toString(),
    ];
    return 'RestTimerState(' + values.join(', ') + ')';
  }
}
