// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'workout_session_model.dart';

// **************************************************************************
// ServiceGenerator
// **************************************************************************

// @FoundryService registration tag for WorkoutSessionModel
// stateful: true
// Generated by foundry_generator — do not edit.

// **************************************************************************
// ServiceStateGenerator
// **************************************************************************

// ignore_for_file: unused_element, annotate_overrides, prefer_interpolation_to_compose_strings

// Generated code for @FoundryServiceState WorkoutSessionState

const _$WorkoutSessionStateSentinel = Object();

/// Whether [WorkoutSessionState] should be persisted automatically.
const bool $WorkoutSessionStateIsPersistent = false;

mixin _$WorkoutSessionStateMixin {
  WorkoutSessionState copyWith({
    Object? isLoading = _$WorkoutSessionStateSentinel,
    Object? isSaving = _$WorkoutSessionStateSentinel,
    Object? activeDraft = _$WorkoutSessionStateSentinel,
    Object? error = _$WorkoutSessionStateSentinel,
  }) {
    final WorkoutSessionState self = this as WorkoutSessionState;
    return WorkoutSessionState(
      isLoading: identical(isLoading, _$WorkoutSessionStateSentinel)
          ? self.isLoading
          : isLoading as bool,
      isSaving: identical(isSaving, _$WorkoutSessionStateSentinel)
          ? self.isSaving
          : isSaving as bool,
      activeDraft: identical(activeDraft, _$WorkoutSessionStateSentinel)
          ? self.activeDraft
          : activeDraft as Workout?,
      error: identical(error, _$WorkoutSessionStateSentinel)
          ? self.error
          : error as String?,
    );
  }

  @override
  bool operator ==(Object other) {
    if (identical(this, other)) return true;
    if (other.runtimeType != runtimeType) return false;
    final WorkoutSessionState self = this as WorkoutSessionState;
    return other is WorkoutSessionState &&
        self.isLoading == other.isLoading &&
        self.isSaving == other.isSaving &&
        self.activeDraft == other.activeDraft &&
        self.error == other.error;
  }

  @override
  int get hashCode {
    final WorkoutSessionState self = this as WorkoutSessionState;
    return Object.hash(
      self.isLoading,
      self.isSaving,
      self.activeDraft,
      self.error,
    );
  }

  @override
  String toString() {
    final WorkoutSessionState self = this as WorkoutSessionState;
    final List<String> values = <String>[
      'isLoading: ' + self.isLoading.toString(),
      'isSaving: ' + self.isSaving.toString(),
      'activeDraft: ' + self.activeDraft.toString(),
      'error: ' + self.error.toString(),
    ];
    return 'WorkoutSessionState(' + values.join(', ') + ')';
  }
}
