import 'package:build/build.dart';
import 'package:source_gen/source_gen.dart';
import 'package:analyzer/dart/element/element.dart';
import 'package:foundry_annotations/foundry_annotations.dart';

/// Generator for @FoundryService annotations.
///
/// Validates:
/// - Stateful services extend `StatefulService<T>`
/// - `dependsOn` types are themselves annotated with `@FoundryService`
///
/// Does NOT generate a class body — users write their own implementation.
class ServiceGenerator extends GeneratorForAnnotation<FoundryService> {
  @override
  Future<String> generateForAnnotatedElement(
    Element element,
    ConstantReader annotation,
    BuildStep buildStep,
  ) async {
    if (element is! ClassElement) {
      throw InvalidGenerationSourceError(
        '@FoundryService can only be used on classes.',
        element: element,
      );
    }

    final classElement = element;
    final className = element.displayName;
    final isStateful = annotation.read('stateful').boolValue;

    // ---- Architecture boundary validation ----
    if (isStateful) {
      final extendsStatefulService = classElement.allSupertypes.any(
        (t) => t.element.name == 'StatefulService',
      );
      if (!extendsStatefulService) {
        throw InvalidGenerationSourceError(
          '@FoundryService(stateful: true) class must extend StatefulService<S>.',
          element: element,
        );
      }
    }

    // Validate dependsOn types are @FoundryService-annotated.
    final dependsOnList = annotation.read('dependsOn');
    if (!dependsOnList.isNull) {
      final dependsList = dependsOnList.listValue;
      for (final dep in dependsList) {
        final depType = dep.toTypeValue()?.element;
        if (depType is ClassElement) {
          final isAnnotatedModel = depType.metadata.any(
            (m) =>
                m.element?.enclosingElement?.name == 'FoundryService' ||
                (m.element is ConstructorElement &&
                    (m.element as ConstructorElement).enclosingElement.name ==
                        'FoundryService'),
          );
          if (!isAnnotatedModel) {
            throw InvalidGenerationSourceError(
              'dependsOn: ${depType.name} must be annotated with @FoundryService.',
              element: element,
            );
          }
        }
      }
    }

    // Emit a registration-tag comment that ContainerGenerator can detect.
    final buffer = StringBuffer();
    buffer.writeln('// @FoundryService registration tag for $className');
    buffer.writeln('// stateful: $isStateful');
    buffer.writeln('// Generated by foundry_generator — do not edit.');

    return buffer.toString();
  }
}
