// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'exercise_repository.dart';

// **************************************************************************
// ModelGenerator
// **************************************************************************

// @FoundryModel registration tag for ExerciseRepository
// stateful: false
// Generated by foundry_generator — do not edit.
