// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'workout_repository.dart';

// **************************************************************************
// ServiceGenerator
// **************************************************************************

// @FoundryService registration tag for WorkoutRepository
// stateful: false
// Generated by foundry_generator — do not edit.
