// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'workout_repository.dart';

// **************************************************************************
// ModelGenerator
// **************************************************************************

// @FoundryModel registration tag for WorkoutRepository
// stateful: false
// Generated by foundry_generator — do not edit.
