// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'app_theme_model.dart';

// **************************************************************************
// ServiceGenerator
// **************************************************************************

// @FoundryService registration tag for AppThemeModel
// stateful: false
// Generated by foundry_generator — do not edit.
