// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'app_theme_model.dart';

// **************************************************************************
// ModelGenerator
// **************************************************************************

// @FoundryModel registration tag for AppThemeModel
// stateful: false
// Generated by foundry_generator — do not edit.
