// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'settings_repository.dart';

// **************************************************************************
// ModelGenerator
// **************************************************************************

// @FoundryModel registration tag for SettingsRepository
// stateful: false
// Generated by foundry_generator — do not edit.
