// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'hive_database_service.dart';

// **************************************************************************
// ModelGenerator
// **************************************************************************

// @FoundryModel registration tag for HiveDatabaseService
// stateful: false
// Generated by foundry_generator — do not edit.
